// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Initialize
#pragma kernel ComputeDistances

StructuredBuffer<float3> _Partial; // 1 entry
RWStructuredBuffer<float> _Distances; // 2 entries

[numthreads(2,1,1)]
void Initialize (uint3 id : SV_DispatchThreadID)
{
    // two threads
}

[numthreads(2,1,1)]
void ComputeDistances(uint3 id : SV_DispatchThreadID)
{
    
}
